### ISSUE TITLE
Erro ao tentar instalar módulo em Prestashop 8.1.2

### ISSUE THREAD

**Issue by RubenMartins** [ifthenpay/prestashop8#1]
Segue o erro recebido:
A instalação do módulo ifthenpay falhou. Hook with the name payment has been registered by Ifthenpay, but the corresponding method hookPayment has not been defined in the Module class.

**Comment by joaocouto-ifthenpay** [comment]
Bom dia,
Desde já lamentamos a resposta tardia.
O módulo foi testado até ao Prestashop 8.1.1, pelo que iremos realizar testes nas versões mais recentes do mesmo. Não obstante, o erro reportado não deverá existir desde a última versão do módulo, lançada em janeiro. Chegou a proceder ao update do módulo? Obrigado.

**Comment by miguelmoleiro** [comment]
Boas João, estou extamente com o mesmo erro na v8.1.7 no Prestashop, a com a atualizacao da ultima versao do modulo à data.

Alguma solução?

**Comment by joaocouto-ifthenpay** [comment]
> Boas João, estou extamente com o mesmo erro na v8.1.7 no Prestashop, a com a atualizacao da ultima versao do modulo à data.
> 
> Alguma solução?

Boa tarde Miguel. 
A nossa equipa ainda não testou o módulo na atual versão do Prestashop (v8.1.7). Em todo o caso, pode verificar se realmente a versão do módulo ifthenpay que está a tentar instalar está na última versão ([v8.1.1](https://github.com/ifthenpay/prestashop8/releases/tag/v8.1.1))? Esta última versão já não regista o hookPayment, pelo que não deverá devolver o warning reportado inicialmente. Poderá estar a referir-se a um hook com uma designação diferente? Obrigado.

**Comment by miguelmoleiro** [comment]
Boas,

Penso ter resolvido, mas tive aparentemente impasses:
- ao reinicializar, por algum motivo desapareceu tabelas, peguei no backup
e refiz.
- depois estive a rever as posições (hooks), e parece ter normalizado.

Envio imagem como está atualmente.

Cumprimentos,
Miguel Moleiro


JOTA ***@***.***> escreveu (quarta, 24/07/2024 à(s) 14:42):

**Comment by joaocouto-ifthenpay** [comment]
Boa tarde,
Pode enviar a imagem novamente? Não recebi qualquer imagem em anexo. Obrigado.

**Comment by Borgas** [comment]
Boa tarde

Já foi testado na versão 8.1.7 ?

**Comment by joaocouto-ifthenpay** [comment]
Boa tarde @Borgas,
Ainda não foram realizados testes nessa versão do Prestashop. Não obstante, gostaríamos de informá-lo que está previsto o início do desenvolvimento de uma nova versão do módulo no próximo mês. Esta nova versão incluirá novos métodos de pagamento e será testada na atual versão do Prestashop (v8.1.7). Assim sendo, já conseguiremos dar feedback relativamente a isso no decorrer do próximo mês.

**Comment by joaocouto-ifthenpay** [comment]
Desde já agradeço pelo feedback de todos, nomeadamente @RubenMartins, @miguelmoleiro e @Borgas.

Conforme referido anteriormente, foi lançada uma nova versão do módulo (v8.2.0), testada e compatível com o Prestashop 8.1.7. Vale referir também que a Gateway de pagamentos da Ifthenpay foi adicionada como novo método de pagamento.

Assim sendo a atual issue será encerrada. Não obstante, qualquer questão que possa surgir, sintam-se à vontade para abrir uma nova.
