### ISSUE TITLE
Encomendas divididas, apenas confirma o pagamento de 1 encomenda e cancela a outra

### ISSUE THREAD

**Issue by Borgas** [ifthenpay/prestashop8#2]
Prestashop 1.7.8.3
Versão 1.3.3

Cenário prestashop:

2 Produtos onde cada um tem o seu método de transporte atribuído.

O cliente ao comprar ambos os produtos, o prestashop divide as encomendas em duas (mesma referencia mas id´s diferentes)
ex: GILTDWDBR#1 GILTDWDBR#2

O montante a pagar é apenas 1, mas não valida ambas as encomendas.
O ifthenpay paga a encomenda #1 mas não paga a encomenda #2

Sei que nesta plataforma não estou a usar a versão mais recente, mas neste momento não convêm fazermos updates, e não sei se este report está ultrapassado.

**Comment by josesoaresif** [comment]
Primeiro, chamo a atenção para o facto de estar a criar este issue no repositório errado, deveria criar no repositório do prestashop 1.7 [ https://github.com/ifthenpay/prestashop1.7](url)

O cenário de múltiplas encomendas geradas pelo Prestashop ao usar diferentes métodos de transporte para produtos distintos nunca foi considerado no desenvolvimento original do módulo. Por isso, o comportamento atual só trata a encomenda principal ao processar o pagamento, o que resulta na não validação da segunda encomenda, isto porque só ocorre um pagamento.

No momento, o módulo não tem suporte para esse tipo de divisão de encomendas. Isso exigiria uma adaptação para que ambas as encomendas fossem tratadas separadamente durante a validação do pagamento (processamento do callback). No entanto, vamos analisar a viabilidade de incluir isso em futuras atualizações.

**Comment by Borgas** [comment]
Bom dia

Não considero no repositório errado, pois é o método de pagamento em si, neste caso o módulo que faz a gestão do pagamento.

Inclusive acrescento que o montante pago pelo cliente, não corresponde ao montante que o prestashop considera pago, ficando o alerta no campo de pagamentos como "montante em falta" quando o cliente paga o total da encomenda.

Compreendo que por defeito o módulo só considere um pagamento, mas refere-se a duas encomendas separadas que são geradas.

Por isso abri aqui o issue, para verificarem o cenário conforme explicado.
Há sempre espaço para melhorar é só isto!
